ajout Lucas Doublet au terraform + actualisation de certains roles P22 et A21
SiMDE-Projects/terraform pull request #113
Opened 2022-09-29 16:49 UTC by leochapp

2022-09-29 16:53 UTC, cesar-richard requested changes

2022-09-29 16:53 UTC, cesar-richard commented on discord_simde/members.tf
> +    (discord_role.integfev.id) = true #resp info A22
Rajoute peut être le rôle de resp info dans ces cas là , ça permet de les contacter d'un coup en cas de besoin

2022-09-29 17:10 UTC, cesar-richard commented on discord_simde/members.tf
> +    (discord_role.integfev.id) = true #resp info A22
Par exemple
```suggestion
    (discord_role.integfev.id) = true #A22
    (discord_role.respinfo.id) = true #integfev A22
```

2022-10-04 18:05 UTC, closed without merging

2022-10-04 18:05 UTC, leochapp commented
j'en refais une avec d'autres changements

2022-10-04 18:09 UTC, cesar-richard commented
tu pouvais continuer celle ci sinon ^^