Ajout Lucas et Alexandre et ajout du channel et role woolly
SiMDE-Projects/terraform pull request #115
Opened 2022-10-05 13:14 UTC by leochapp

2022-10-05 13:55 UTC, cesar-richard requested changes

2022-10-05 13:55 UTC, cesar-richard commented on discord_simde/members.tf
> +  }
La CI confirme que tu ne peux pas créer un block de role sans au minimum un role dedans

![image](https://user-images.githubusercontent.com/5199868/194078097-edae2363-d324-4a4f-8d20-63e989d8a136.png)

2022-10-09 10:57 UTC, leochapp commented on discord_simde/members.tf
> +  }
résolu

2022-10-09 14:48 UTC, cesar-richard approved these changes

2022-10-09 14:48 UTC, merged